#!/bin/bash
# 部署运行 `sh deploy`
# @farwish

# 依赖
if test -f composer.lock; then
    composer update --prefer-dist --no-dev
else
    composer install --prefer-dist --no-dev
    # 应用配置
    cp ./app/config/config.ini.default ./app/config/config.ini
fi

# 搜索配置
cp ./app/xsconfig/*.ini ./vendor/hightman/xunsearch/app/
