#!/bin/bash
# 部署运行 `sh deploy`
# @farwish

if test -f composer.lock; then
    composer update --prefer-dist --no-dev
else
    composer install --prefer-dist --no-dev
    # 应用配置,view cache.
    cp ./app/config/config.ini.default ./app/config/config.ini
    mkdir ./app/cache
fi
